// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vued.DAL;

#nullable disable

namespace Vued.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250525162641_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Vued.DAL.Entities.GenreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Drama"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Romance"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Crime"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Name = "Western"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Name = "Historical"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Name = "War"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Name = "Biography"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Name = "Musical"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Name = "Animation"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Name = "Family"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Name = "Sport"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Name = "Superhero"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Name = "Noir"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            Name = "Satire"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            Name = "Parody"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            Name = "Psychological"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            Name = "Post-Apocalyptic"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            Name = "Dystopian"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            Name = "Coming-of-Age"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            Name = "Epic"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            Name = "Period"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            Name = "Political"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            Name = "Slice of Life"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            Name = "Supernatural"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            Name = "Survival"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            Name = "Espionage"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            Name = "Heist"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            Name = "Disaster"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            Name = "Martial Arts"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            Name = "Road Movie"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            Name = "Anthology"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            Name = "Experimental"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            Name = "Gothic"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            Name = "Steampunk"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            Name = "Cyberpunk"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            Name = "Dark Comedy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000046"),
                            Name = "Romantic Comedy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000047"),
                            Name = "Tragedy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000048"),
                            Name = "Melodrama"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000049"),
                            Name = "Mockumentary"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            Name = "Silent Film"
                        });
                });

            modelBuilder.Entity("Vued.DAL.Entities.MediaFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Favourite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseDate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaFileEntity");

                    b.HasDiscriminator().HasValue("MediaFileEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Vued.DAL.Entities.MediaFileGenreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaFileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MediaFileId", "GenreId")
                        .IsUnique();

                    b.ToTable("MediaFileGenreEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000001"),
                            MediaFileId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            GenreId = new Guid("00000000-0000-0000-0000-000000000003"),
                            MediaFileId = new Guid("20000000-0000-0000-0000-000000000008")
                        });
                });

            modelBuilder.Entity("Vued.DAL.Entities.WatchlistEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Watchlists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Description = "Top-rated movies and series",
                            Name = "My Favorites"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Description = "Movies and series to watch later",
                            Name = "Watch Later"
                        });
                });

            modelBuilder.Entity("Vued.DAL.Entities.WatchlistMediaFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaFileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WatchlistId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("WatchlistId", "MediaFileId")
                        .IsUnique();

                    b.ToTable("WatchlistMediaFileEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            MediaFileId = new Guid("10000000-0000-0000-0000-000000000004"),
                            WatchlistId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            MediaFileId = new Guid("20000000-0000-0000-0000-000000000008"),
                            WatchlistId = new Guid("30000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("Vued.DAL.Entities.MovieEntity", b =>
                {
                    b.HasBaseType("Vued.DAL.Entities.MediaFileEntity");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("MovieEntity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "A computer hacker learns about the true nature of reality and joins a group of rebels to fight a war against powerful controllers.",
                            Director = "Lana Wachowski, Lilly Wachowski",
                            Duration = 0,
                            Favourite = true,
                            Name = "The Matrix",
                            Rating = "8/10",
                            ReleaseDate = 1999,
                            Status = 2,
                            URL = "https://www.imdb.com/title/tt0133093/",
                            Length = 136
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "The life story of a man with a low IQ who achieves extraordinary feats through his kindness and determination.",
                            Director = "Robert Zemeckis",
                            Duration = 0,
                            Favourite = true,
                            Name = "Forrest Gump",
                            Rating = "6/10",
                            ReleaseDate = 1994,
                            Status = 2,
                            URL = "https://www.imdb.com/title/tt0109830/",
                            Length = 142
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.",
                            Director = "Stanley Kubrick",
                            Duration = 0,
                            Favourite = false,
                            Name = "The Shining",
                            Rating = "7/10",
                            ReleaseDate = 1980,
                            Status = 2,
                            URL = "https://www.imdb.com/title/tt0081505/",
                            Length = 144
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "A skilled thief with the ability to enter dreams must pull off an impossible heist: planting an idea in someone's mind.",
                            Director = "Christopher Nolan",
                            Duration = 0,
                            Favourite = true,
                            Name = "Inception",
                            Rating = "9/10",
                            ReleaseDate = 2010,
                            Status = 2,
                            URL = "https://www.imdb.com/title/tt1375666/",
                            Length = 148
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Description = "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
                            Director = "Francis Ford Coppola",
                            Duration = 0,
                            Favourite = true,
                            Name = "The Godfather",
                            Rating = "8/10",
                            ReleaseDate = 1972,
                            Status = 2,
                            URL = "https://www.imdb.com/title/tt0068646/",
                            Length = 175
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Description = "A young girl becomes trapped in a strange spirit world and must find a way to free herself and her parents.",
                            Director = "Hayao Miyazaki",
                            Duration = 0,
                            Favourite = false,
                            Name = "Spirited Away",
                            Rating = "8/10",
                            ReleaseDate = 2001,
                            Status = 2,
                            URL = "https://www.imdb.com/title/tt0245429/",
                            Length = 125
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Description = "In a post-apocalyptic wasteland, a drifter and a rebel leader fight to survive against a tyrannical ruler.",
                            Director = "George Miller",
                            Duration = 0,
                            Favourite = true,
                            Name = "Mad Max: Fury Road",
                            Rating = "7/10",
                            ReleaseDate = 2015,
                            Status = 2,
                            URL = "https://www.imdb.com/title/tt1392190/",
                            Length = 120
                        });
                });

            modelBuilder.Entity("Vued.DAL.Entities.SeriesEntity", b =>
                {
                    b.HasBaseType("Vued.DAL.Entities.MediaFileEntity");

                    b.Property<int>("NumberOfEpisodes")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("SeriesEntity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Description = "A chemistry teacher turned drug-lord teams up with a former student to build a methamphetamine empire.",
                            Director = "Vince Gilligan",
                            Duration = 0,
                            Favourite = true,
                            Name = "Breaking Bad",
                            Rating = "10/10",
                            ReleaseDate = 2008,
                            Status = 2,
                            URL = "https://www.imdb.com/title/tt0903747/",
                            NumberOfEpisodes = 62
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Description = "A group of friends in the 1980s uncover supernatural mysteries and government conspiracies in their small town.",
                            Director = "The Duffer Brothers",
                            Duration = 0,
                            Favourite = true,
                            Name = "Stranger Things",
                            Rating = "8/10",
                            ReleaseDate = 2016,
                            Status = 1,
                            URL = "https://www.imdb.com/title/tt4574334/",
                            NumberOfEpisodes = 34
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            Description = "A mockumentary about the daily lives of employees at the Dunder Mifflin paper company.",
                            Director = "Greg Daniels",
                            Duration = 0,
                            Favourite = true,
                            Name = "The Office (US)",
                            Rating = "9/10",
                            ReleaseDate = 2005,
                            Status = 2,
                            URL = "https://www.imdb.com/title/tt0386676/",
                            NumberOfEpisodes = 201
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            Description = "Noble families fight for control of the Iron Throne in a fantasy world filled with dragons and political intrigue.",
                            Director = "David Benioff, D.B. Weiss",
                            Duration = 0,
                            Favourite = true,
                            Name = "Game of Thrones",
                            Rating = "9/10",
                            ReleaseDate = 2011,
                            Status = 2,
                            URL = "https://www.imdb.com/title/tt0944947/",
                            NumberOfEpisodes = 73
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            Description = "A lone bounty hunter navigates the outer reaches of the galaxy, protecting a mysterious baby Yoda.",
                            Director = "Jon Favreau",
                            Duration = 0,
                            Favourite = false,
                            Name = "The Mandalorian",
                            Rating = "6/10",
                            ReleaseDate = 2019,
                            Status = 1,
                            URL = "https://www.imdb.com/title/tt8111088/",
                            NumberOfEpisodes = 24
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            Description = "An anthology series exploring the dark side of technology and human nature in dystopian futures.",
                            Director = "Charlie Brooker",
                            Duration = 0,
                            Favourite = false,
                            Name = "Black Mirror",
                            Rating = "8/10",
                            ReleaseDate = 2011,
                            Status = 1,
                            URL = "https://www.imdb.com/title/tt2085059/",
                            NumberOfEpisodes = 27
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            Description = "A biographical drama chronicling the reign of Queen Elizabeth II and major historical events.",
                            Director = "Peter Morgan",
                            Duration = 0,
                            Favourite = false,
                            Name = "The Crown",
                            Rating = "-",
                            ReleaseDate = 2016,
                            Status = 0,
                            URL = "https://www.imdb.com/title/tt4786824/",
                            NumberOfEpisodes = 60
                        });
                });

            modelBuilder.Entity("Vued.DAL.Entities.MediaFileGenreEntity", b =>
                {
                    b.HasOne("Vued.DAL.Entities.GenreEntity", "Genre")
                        .WithMany("MediaFileGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vued.DAL.Entities.MediaFileEntity", "MediaFile")
                        .WithMany("MediaFileGenres")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("Vued.DAL.Entities.WatchlistMediaFileEntity", b =>
                {
                    b.HasOne("Vued.DAL.Entities.MediaFileEntity", "MediaFile")
                        .WithMany("WatchlistMediaFiles")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vued.DAL.Entities.WatchlistEntity", "Watchlist")
                        .WithMany("WatchlistMediaFiles")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("Vued.DAL.Entities.GenreEntity", b =>
                {
                    b.Navigation("MediaFileGenres");
                });

            modelBuilder.Entity("Vued.DAL.Entities.MediaFileEntity", b =>
                {
                    b.Navigation("MediaFileGenres");

                    b.Navigation("WatchlistMediaFiles");
                });

            modelBuilder.Entity("Vued.DAL.Entities.WatchlistEntity", b =>
                {
                    b.Navigation("WatchlistMediaFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
